export const scoringListData = [
  {
    id: 'record-1',
    stt: '01',
    studentName: 'Nguyễn Thị Mai',
    studentEmail: 'nguyenmai@huit.edu.vn',
    avatar: 'https://i.pravatar.cc/150?img=47',
    studentId: '2001223660',
    faculty: 'Công nghệ thông tin',
    className: '13DHTT02',
    activityTitle: 'Hiến máu nhân đạo tháng 10',
    activityId: 'activity-1',
    activityDate: '23/10/2024',
    score: 10,
    checkIn: { icon: 'tick', time: '08:20:22', status: 'Đúng giờ' },
    checkOut: { icon: 'tick', time: '11:45:08', status: 'Đúng giờ' },
    statusLabel: 'Chờ duyệt',
    statusKey: 'pending',
  },
  {
    id: 'record-2',
    stt: '02',
    studentName: 'Nguyễn Văn Bảo',
    studentEmail: 'nguyenbao@huit.edu.vn',
    avatar: 'https://i.pravatar.cc/150?img=52',
    studentId: '2001223888',
    faculty: 'Công nghệ thông tin',
    className: '13DHTT02',
    activityTitle: 'Hiến máu nhân đạo tháng 10',
    activityId: 'activity-1',
    activityDate: '23/10/2024',
    score: 10,
    checkIn: { icon: 'alert', time: '08:42:16', status: 'Trễ giờ' },
    checkOut: { icon: 'tick', time: '11:30:12', status: 'Đúng giờ' },
    statusLabel: 'Chờ duyệt',
    statusKey: 'pending',
  },
  {
    id: 'record-3',
    stt: '03',
    studentName: 'Phạm Thùy Linh',
    studentEmail: 'phamlinh@huit.edu.vn',
    avatar: 'https://i.pravatar.cc/150?img=15',
    studentId: '2001223770',
    faculty: 'Công nghệ sinh học',
    className: '12DHSH01',
    activityTitle: 'Chạy bộ gây quỹ mùa đông',
    activityId: 'activity-2',
    activityDate: '09/11/2024',
    score: 8,
    checkIn: { icon: 'tick', time: '06:55:02', status: 'Đúng giờ' },
    checkOut: { icon: 'alert', time: '10:05:41', status: 'Trễ giờ' },
    statusLabel: 'Đạt',
    statusKey: 'approved',
  },
  {
    id: 'record-4',
    stt: '04',
    studentName: 'Trần Gia Huy',
    studentEmail: 'tranhuy@huit.edu.vn',
    avatar: 'https://i.pravatar.cc/150?img=33',
    studentId: '2001223650',
    faculty: 'Kinh tế',
    className: '11DHKD03',
    activityTitle: 'Tình nguyện mùa hè xanh',
    activityId: 'activity-3',
    activityDate: '15/07/2024',
    score: 12,
    checkIn: { icon: 'x', time: '—', status: 'Vắng mặt' },
    checkOut: { icon: 'x', time: '—', status: 'Vắng mặt' },
    statusLabel: 'Không đạt',
    statusKey: 'rejected',
  },
  {
    id: 'record-5',
    stt: '05',
    studentName: 'Huỳnh Hải Đăng',
    studentEmail: 'huynhdang@huit.edu.vn',
    avatar: 'https://i.pravatar.cc/150?img=68',
    studentId: '2001223201',
    faculty: 'Công nghệ thông tin',
    className: '13DHTT03',
    activityTitle: 'Chuyến xe yêu thương',
    activityId: 'activity-4',
    activityDate: '05/12/2024',
    score: 9,
    checkIn: { icon: 'tick', time: '07:15:46', status: 'Đúng giờ' },
    checkOut: { icon: 'tick', time: '12:12:22', status: 'Đúng giờ' },
    statusLabel: 'Đạt',
    statusKey: 'approved',
  },
];

export default scoringListData;
