export const scoringListData = [
  {
    stt: '01',
    tenSinhVien: 'Nguyễn Thị Mai',
    email: 'nguyenmai@huit.edu.vn',
    avatar: 'https://i.pravatar.cc/150?img=47',
    mssv: '2001223660',
    khoa: 'Công nghệ thông tin',
    lop: '13DHTT02',
    hoatDong: 'Hiến máu nhân đạo tháng 10',
    ngayHoatDong: '15/12/2024',
    diem: 10,
    checkIn: { icon: 'tick', time: '08:20:22', status: 'Đúng giờ' },
    checkOut: { icon: 'tick', time: '08:20:22', status: 'Đúng giờ' },
    trangThai: 'Chờ duyệt',
  },
  {
    stt: '02',
    tenSinhVien: 'Nguyễn Thị Mai',
    email: 'nguyenmai@huit.edu.vn',
    avatar: 'https://i.pravatar.cc/150?img=47',
    mssv: '2001223660',
    khoa: 'Công nghệ thông tin',
    lop: '13DHTT02',
    hoatDong: 'Hiến máu nhân đạo tháng 10',
    ngayHoatDong: '15/12/2024',
    diem: 10,
    checkIn: { icon: 'alert', time: '08:20:22', status: 'Trễ giờ' },
    checkOut: { icon: 'tick', time: '08:20:22', status: 'Đúng giờ' },
    trangThai: 'Chờ duyệt',
  },
  {
    stt: '03',
    tenSinhVien: 'Nguyễn Thị Mai',
    email: 'nguyenmai@huit.edu.vn',
    avatar: 'https://i.pravatar.cc/150?img=47',
    mssv: '2001223660',
    khoa: 'Công nghệ thông tin',
    lop: '13DHTT02',
    hoatDong: 'Hiến máu nhân đạo tháng 10',
    ngayHoatDong: '15/12/2024',
    diem: 10,
    checkIn: { icon: 'x', time: '08:20:22', status: 'Vắng mặt' },
    checkOut: { icon: 'x', time: '08:20:22', status: 'Vắng mặt' },
    trangThai: 'Không đạt',
  },
  {
    stt: '04',
    tenSinhVien: 'Nguyễn Thị Mai',
    email: 'nguyenmai@huit.edu.vn',
    avatar: 'https://i.pravatar.cc/150?img=47',
    mssv: '2001223660',
    khoa: 'Công nghệ thông tin',
    lop: '13DHTT02',
    hoatDong: 'Hiến máu nhân đạo tháng 10',
    ngayHoatDong: '15/12/2024',
    diem: 10,
    checkIn: { icon: 'tick', time: '08:20:22', status: 'Đúng giờ' },
    checkOut: { icon: 'tick', time: '08:20:22', status: 'Đúng giờ' },
    trangThai: 'Đạt',
  },
];
