export const scoringDetailRecords = {
  'record-1': {
    id: 'record-1',
    statusKey: 'pending',
    statusLabel: 'Chờ duyệt',
    points: 10,
    submittedAt: '08:20 23/10/2024',
    activity: {
      id: 'activity-1',
      title: 'Hoạt động thiện nguyện cộng đồng - Trao tặng học bổng',
      type: 'Tình nguyện',
      organization: 'Đoàn khoa Công nghệ thông tin',
      location: 'Cơ sở Thủ Đức - HUIT',
      room: 'Nhà thi đấu Thành phố Thủ Đức',
      startTime: '07:30 23/10/2024',
      endTime: '11:45 23/10/2024',
      supervisor: 'Nguyễn Văn An',
    },
    student: {
      name: 'Nguyễn Thị Mai',
      studentId: '2001223660',
      email: '2001223660@student.huit.edu.vn',
      phone: '0912 345 678',
      faculty: 'Công nghệ thông tin',
      className: '13DHTT02',
      course: 'K14',
      avatar: 'https://i.pravatar.cc/240?img=47',
    },
    attendance: {
      checkIn: {
        time: '08:20 23/10/2024',
        status: 'Đúng giờ',
        note: 'Có mặt tại điểm danh A1',
        image: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80',
      },
      checkOut: {
        time: '11:45 23/10/2024',
        status: 'Đúng giờ',
        note: 'Hoàn thành nhiệm vụ tại khu vực quầy lễ tân',
        image: 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=800&q=80',
      },
    },
    history: [
      {
        id: 'history-1',
        time: '23/10/2024 - 08:20',
        actor: 'Nguyễn Thị Mai',
        action: 'Nộp minh chứng điểm danh',
        status: 'submitted',
      },
      {
        id: 'history-2',
        time: '23/10/2024 - 09:00',
        actor: 'Hệ thống',
        action: 'Tự động ghi nhận điểm danh Check-in',
        status: 'processing',
      },
      {
        id: 'history-3',
        time: '23/10/2024 - 12:00',
        actor: 'Admin CTXH',
        action: 'Đang chấm minh chứng minh bạch',
        status: 'pending',
      },
    ],
  },
  'record-2': {
    id: 'record-2',
    statusKey: 'pending',
    statusLabel: 'Chờ duyệt',
    points: 10,
    submittedAt: '08:35 23/10/2024',
    activity: {
      id: 'activity-1',
      title: 'Hoạt động thiện nguyện cộng đồng - Trao tặng học bổng',
      type: 'Tình nguyện',
      organization: 'Đoàn khoa Công nghệ thông tin',
      location: 'Cơ sở Thủ Đức - HUIT',
      room: 'Nhà thi đấu Thành phố Thủ Đức',
      startTime: '07:30 23/10/2024',
      endTime: '11:45 23/10/2024',
      supervisor: 'Nguyễn Văn An',
    },
    student: {
      name: 'Nguyễn Văn Bảo',
      studentId: '2001223888',
      email: '2001223888@student.huit.edu.vn',
      phone: '0903 512 468',
      faculty: 'Công nghệ thông tin',
      className: '13DHTT02',
      course: 'K14',
      avatar: 'https://i.pravatar.cc/240?img=52',
    },
    attendance: {
      checkIn: {
        time: '08:42 23/10/2024',
        status: 'Trễ giờ',
        note: 'Có mặt tại điểm danh A1 sau 10 phút',
        image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
      },
      checkOut: {
        time: '11:30 23/10/2024',
        status: 'Đúng giờ',
        note: 'Bàn giao lại khu vực trực và hoàn tất nhiệm vụ',
        image: 'https://images.unsplash.com/photo-1526498460520-4c246339dccb?auto=format&fit=crop&w=800&q=80',
      },
    },
    history: [
      {
        id: 'history-2-1',
        time: '23/10/2024 - 08:42',
        actor: 'Nguyễn Văn Bảo',
        action: 'Nộp minh chứng điểm danh',
        status: 'submitted',
      },
      {
        id: 'history-2-2',
        time: '23/10/2024 - 09:10',
        actor: 'Hệ thống',
        action: 'Ghi nhận trạng thái đến trễ',
        status: 'pending',
      },
    ],
  },
  'record-3': {
    id: 'record-3',
    statusKey: 'approved',
    statusLabel: 'Đạt',
    points: 8,
    submittedAt: '07:05 09/11/2024',
    activity: {
      id: 'activity-2',
      title: 'Chạy bộ gây quỹ mùa đông',
      type: 'Thể thao cộng đồng',
      organization: 'Đoàn trường HUIT',
      location: 'Quận 7 - TP.HCM',
      room: 'Công viên Ánh Sáng',
      startTime: '06:30 09/11/2024',
      endTime: '10:30 09/11/2024',
      supervisor: 'Trần Nhật Hào',
    },
    student: {
      name: 'Phạm Thùy Linh',
      studentId: '2001223770',
      email: '2001223770@student.huit.edu.vn',
      phone: '0987 631 245',
      faculty: 'Công nghệ sinh học',
      className: '12DHSH01',
      course: 'K13',
      avatar: 'https://i.pravatar.cc/240?img=15',
    },
    attendance: {
      checkIn: {
        time: '06:55 09/11/2024',
        status: 'Đúng giờ',
        note: 'Có mặt tại quầy tiếp đón tình nguyện viên',
        image: 'https://images.unsplash.com/photo-1520975922074-1bde0df02e9d?auto=format&fit=crop&w=800&q=80',
      },
      checkOut: {
        time: '10:05 09/11/2024',
        status: 'Trễ giờ',
        note: 'Hoàn thành phần chia quà muộn hơn dự kiến 5 phút',
        image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=80',
      },
    },
    history: [
      {
        id: 'history-3-1',
        time: '09/11/2024 - 11:00',
        actor: 'Admin CTXH',
        action: 'Xác nhận điểm danh và duyệt điểm',
        status: 'approved',
      },
    ],
  },
  'record-4': {
    id: 'record-4',
    statusKey: 'rejected',
    statusLabel: 'Không đạt',
    points: 12,
    submittedAt: '16:15 15/07/2024',
    activity: {
      id: 'activity-3',
      title: 'Tình nguyện mùa hè xanh',
      type: 'Tình nguyện dài ngày',
      organization: 'Đoàn khoa Kinh tế',
      location: 'Huyện Cần Giờ - TP.HCM',
      room: 'Điểm trường An Thới Đông',
      startTime: '07:00 15/07/2024',
      endTime: '17:30 15/07/2024',
      supervisor: 'Phạm Minh Trí',
    },
    student: {
      name: 'Trần Gia Huy',
      studentId: '2001223650',
      email: '2001223650@student.huit.edu.vn',
      phone: '0975 222 891',
      faculty: 'Kinh tế',
      className: '11DHKD03',
      course: 'K12',
      avatar: 'https://i.pravatar.cc/240?img=33',
    },
    attendance: {
      checkIn: {
        time: '—',
        status: 'Vắng mặt',
        note: 'Chưa ghi nhận minh chứng check-in',
      },
      checkOut: {
        time: '—',
        status: 'Vắng mặt',
        note: 'Không có dữ liệu check-out',
      },
    },
    history: [
      {
        id: 'history-4-1',
        time: '15/07/2024 - 18:00',
        actor: 'Admin CTXH',
        action: 'Từ chối minh chứng do thiếu dữ liệu điểm danh',
        status: 'rejected',
      },
    ],
  },
  'record-5': {
    id: 'record-5',
    statusKey: 'approved',
    statusLabel: 'Đạt',
    points: 9,
    submittedAt: '07:30 05/12/2024',
    activity: {
      id: 'activity-4',
      title: 'Chuyến xe yêu thương',
      type: 'Tình nguyện',
      organization: 'Đoàn khoa Công nghệ thông tin',
      location: 'Cơ sở Quận 9 - HUIT',
      room: 'Sảnh chính toà nhà A',
      startTime: '06:45 05/12/2024',
      endTime: '12:30 05/12/2024',
      supervisor: 'Võ Hải Yến',
    },
    student: {
      name: 'Huỳnh Hải Đăng',
      studentId: '2001223201',
      email: '2001223201@student.huit.edu.vn',
      phone: '0934 785 120',
      faculty: 'Công nghệ thông tin',
      className: '13DHTT03',
      course: 'K14',
      avatar: 'https://i.pravatar.cc/240?img=68',
    },
    attendance: {
      checkIn: {
        time: '07:15 05/12/2024',
        status: 'Đúng giờ',
        note: 'Điểm danh tại khu vực sân trường',
        image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=800&q=80',
      },
      checkOut: {
        time: '12:12 05/12/2024',
        status: 'Đúng giờ',
        note: 'Bàn giao lại dụng cụ và hoàn tất nhật ký hoạt động',
        image: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80',
      },
    },
    history: [
      {
        id: 'history-5-1',
        time: '05/12/2024 - 13:00',
        actor: 'Admin CTXH',
        action: 'Duyệt điểm và cập nhật vào hệ thống',
        status: 'approved',
      },
    ],
  },
};

export const getScoringDetailRecord = (id) => scoringDetailRecords[id] || scoringDetailRecords['record-1'];

export default scoringDetailRecords;
